export const departments = [
  "Fashion Design",
  "Textile Technology",
  "Fashion Marketing",
  "Pattern Making & Garment Construction",
  "Fashion Merchandising",
  "Apparel Production",
  "Fashion Illustration",
  "Fashion Styling",
  "Accessory Design",
  "Footwear Design",
  "Fashion Photography",
  "Visual Merchandising",
  "Sustainable Fashion",
  "Fabric Science",
  "Costume Design",
  "Fashion Communication",
  "Fashion Business Management",
  "Fashion Technology",
  "Jewelry Design",
  "Fashion Entrepreneurship",
];
